### ISSUE TITLE
Back - Consultar contato (número/email)

### ISSUE THREAD

**Issue by Rickjoim** [franklaercio/contact-verify#1]
Deve ser desenvolvido um endpoint que, utilizando o número passado pelo usuário como parâmetro, irá verificar na base de dados se possui vínculo com alguma empresa listada.

Se possuir vínculo, irá retornar o nome e o cnpj da empresa e um status ok.
Se não possuir vínculo, irá retornar status alerta.

**Comment by franklaercio** [comment]
You can view the pull request details here: [GitHub Pull Request #5](https://github.com/franklaercio/contact-verify/pull/6).
