### ISSUE TITLE
Back - Inserir contato (número/email)

### ISSUE THREAD

**Issue by Rickjoim** [franklaercio/contact-verify#2]
Cada número ou email pesquisado deve ser cadastrado em banco para que seja mantido um controle de quantas pessoas receberam ligação ou mensagem daquele contato.

O front irá fazer uma validação para que seja possível utilizar apenas números e emails válidos.

**Comment by franklaercio** [comment]
You can view the pull request details here: [GitHub Pull Request #5](https://github.com/franklaercio/contact-verify/pull/5).
